In [17]:
import os
import sys

# 현재 파일의 절대 경로를 기준으로 부모 디렉토리 설정
sys.path.append(os.pardir)

import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss


In [11]:
net = simpleNet()
print(net.W)

[[-1.36305632  0.1199361  -0.66390926]
 [ 1.98097846 -1.16902441 -0.61682757]]


In [12]:
x = np.array([0.6,0.9])
p = net.predict(x)
print(p)

[ 0.96504682 -0.98016031 -0.95349037]


In [13]:
np.argmax(p)

np.int64(0)

In [14]:
t = np.array([0, 0, 1]) # 정답 레이블
net.loss(x, t)

np.float64(2.1730073397840766)

In [15]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.4651955   0.06650324 -0.53169874]
 [ 0.69779325  0.09975486 -0.7975481 ]]


In [16]:
f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)